### ISSUE TITLE
Gutenberg Limitations for Nwaneri Portfolio theme

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#1]
### Overview
Working on a portfolio block-based theme (#2), I am coming across issues implementing the design as presented. I'm keeping track of those issues here so I don't forget to investigate it further in the Gutenberg repository or open up enhancement issues there.

**Add the post date** 
I came across an instance where I wanted to be able to add the post date via a block:

<img width="514" alt="Screen Shot 2020-01-27 at 2 26 49 PM" src="https://user-images.githubusercontent.com/5375500/73206604-2dfc9980-4111-11ea-860b-2e30a90c35e9.png">

~~There's no way to do so via Gutenberg core blocks to my knowledge.~~ 

This was added as of Gutenberg 7.3.

**Add the comments for a single post** 
There is the Latest Comments block, but they are not respective / specific to the post that you're adding the block to: 

<img width="399" alt="Screen Shot 2020-01-27 at 4 06 09 PM" src="https://user-images.githubusercontent.com/5375500/73213884-0ca2aa00-411f-11ea-9d22-f6fa342d0271.png">

Being partially addressed by https://github.com/WordPress/gutenberg/pull/19953 and https://github.com/WordPress/gutenberg/pull/19954

Opened https://github.com/WordPress/gutenberg/issues/20054

**Post Date block does not accept additional classes via the block inspector**

Hopefully being addressed by https://github.com/WordPress/gutenberg/issues/19697 

**There is no block for post tags or categories**

Addressed by https://github.com/WordPress/gutenberg/pull/19580

**The controls for how the Latest Posts block is displayed are limited e.g. no control over column width**

Addressed by query and Post block https://github.com/WordPress/gutenberg/issues/15623

**Can't style the Social Links block to be text driven because there is no text within the link, it's an SVG**

<img width="449" alt="Screen Shot 2020-01-29 at 2 26 09 PM" src="https://user-images.githubusercontent.com/5375500/73390110-7481fd80-42a3-11ea-8d98-11ef1bae1ce5.png">

**Comment by kjellr** [comment]
I'm going to close this one for now since we're moving this repo over to [automattic/themes](https://github.com/automattic/themes), but the issue will still be readable here for posterity.
