### ISSUE TITLE
Varya: Tiny font preset is not styled correctly in the editor or front end 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#100]
![Screen Shot 2020-04-16 at 6 10 43 PM](https://user-images.githubusercontent.com/1202812/79512039-9bcca900-800e-11ea-87db-1db464b35bf1.png)

To reproduce: 

1. Add a paragraph block
2. Use the sidebar to choose the "Tiny" [font preset](https://cloudup.com/cUg0KHgHP6A).
3. Note that the text should be 14px, but instead it appears to be 18px.

**Comment by jffng** [comment]
For me, this is a front-end issue only. The editor displays the tiny size correctly (14px).
