### ISSUE TITLE
Varya: Some left and right-aligned blocks appear out of place on the front end

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#105]
These should appear tucked into the text column, like left and right images do. Instead, they are pushed all the way out to the far edges of the window right now: 

![Screen Shot 2020-04-16 at 6 41 31 PM](https://user-images.githubusercontent.com/1202812/79513516-0af7cc80-8012-11ea-9008-195899bec487.png)
![Screen Shot 2020-04-16 at 6 41 38 PM](https://user-images.githubusercontent.com/1202812/79513517-0b906300-8012-11ea-88ce-e5f456bdc55e.png)

This occurs with: 

- Video Block
- File Block
- Pullquote

**Comment by allancole** [comment]
File Block alignments are fixed in https://github.com/Automattic/themes-workspace/pull/118 👍
