### ISSUE TITLE
Gutenberg + Block-based theme test resources

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#11]
**Description**
It would be useful to have up-to-date resources that make it straightforward to develop and QA new Gutenberg ready + block-based themes. For example:

- An xml with content and layet. We could start with the same one that's being used for Premium Theme testing: https://cloudup.com/cHpGcye_aQJ 
- An associated `header.html` with a navigation block that links to all of those pages. 
To that end, I created a gist for now: https://gist.github.com/jffng/88856c80f49a0695ef71845b10d750a2 

What are other resources that might be helpful?

**Comment by ianstewart** [comment]
Theme preview tools/plugins for quickly switching themes on the front-end for quick testing? We have an internal tool on WP.com that we use. There may be a dot org plugin that does something similar.

**Comment by kjellr** [comment]
I'm going to close this one for now since we're moving this repo over to [automattic/themes](https://github.com/automattic/themes), but the issue will still be readable here for posterity.
