### ISSUE TITLE
Varya: customizer color contrast accessibility

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#129]
Follows #94 and #113. 

It would be ideal to warn the user when they create inaccessible color combinations using the customizer.

In Gutenberg, these warnings appear automatically in the block's color settings:

<img width="282" alt="Screen Shot 2020-04-24 at 4 30 38 PM" src="https://user-images.githubusercontent.com/5375500/80254389-1027cd80-8649-11ea-9cf7-3cf9c55b435b.png">

To-do:
- [x] Research and identify color processing utilities that can be leveraged in the customizer
- [ ] Determine which combinations of variables need to be evaluated
- [ ] Implement the color processing utilities and subsequent warnings

**Comment by kjellr** [comment]
https://github.com/soderlind/2016-customizer-demo
This appears pretty close to what we're looking to do, and it's GPL-licensed:

![wcag-color-contrast](https://user-images.githubusercontent.com/1202812/81074418-f8591080-8eb6-11ea-9976-26ff177cfd6f.gif)

**Comment by jffng** [comment]
Working off of #113, I've got the bones of this working, but the UX is pretty miserable:

![Kapture 2020-05-07 at 12 15 57](https://user-images.githubusercontent.com/5375500/81318820-cb466280-905c-11ea-9826-1d6214212b31.gif)

A few thoughts:
- I wish the notification weren't so disruptive, and that I could control its position. Maybe I can with some customizer specific CSS?
- How should we handle displaying multiple conflicts? I feel like there should only be a single notification, noting all of the violations.
- What should this text say?

These feel like questions to address in a PR, but would like to get #113 merged first.

**Comment by kjellr** [comment]
> How should we handle displaying multiple conflicts? I feel like there should only be a single notification, noting all of the violations.

Yeah, just one notification is fine. More than that is overkill. 

> What should this text say?

I think we should just use the same language that's in the Gutenberg one (or something really close to it): "This color combination may be hard for people to read. Try using a brighter background color and/or a darker text color."
