### ISSUE TITLE
Varya: Featured image treatment

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#136]
Currently if a post has a featured image, it displays at the full resolution of the image:

<img width="1000" alt="Screen Shot 2020-05-01 at 12 26 16 PM" src="https://user-images.githubusercontent.com/5375500/80821633-1bc64780-8ba7-11ea-9ed0-9fdf8a76796a.png">

As far as I know, there's no way to control the size of the featured image from the editor. How should this be handled? Should we add styles to set a max-width e.g. to the theme's default width?

**Comment by kjellr** [comment]
Hmm that's a good question. I think we should keep these full-width on the single post pages, but I do think it makes sense to limit the width on any archive pages or search results. I'll open a quick PR.
