### ISSUE TITLE
Seedlet: using one variables file

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#140]
I've been thinking about the reason that two separate variable files (one for the editor and one for the front-end) are still needed.

As far as I can tell, the main difference is that the [editor variables styles](https://github.com/Automattic/themes-workspace/blob/dd829241cc5fc28bc62477aae512487eb12b781e/varya/assets/css/variables-editor.css#L24) target the `body`, and the [front-end](https://github.com/Automattic/themes-workspace/blob/dd829241cc5fc28bc62477aae512487eb12b781e/varya/assets/css/variables.css#L24) targets `:root`. 

What is the reason for this distinction? Could we use the same level of targeting and share the file?  

-----------

This led me to another question around how we're enqueuing the editor variables:

https://github.com/Automattic/themes-workspace/blob/dd829241cc5fc28bc62477aae512487eb12b781e/varya/classes/class-varya-custom-colors.php#L259

I find it a bit misleading from a code readability perspective. I assume that enqueuing the variables here is necessary to have custom colors work in the editor, but I would expect that the call to would happen in the main `functions.php` file [here](https://github.com/Automattic/themes-workspace/blob/dd829241cc5fc28bc62477aae512487eb12b781e/varya/functions.php#L109-L113), within the `add_editor_style` function call.

cc @kjellr @allancole

**Comment by kjellr** [comment]
Allan can probably speak more to the first question. As for this one: 

> I assume that enqueuing the variables here is necessary to have custom colors work in the editor, but I would expect that the call to would happen in the main functions.php file here, within the add_editor_style function call.

Yeah, we could include it here instead — the only reason I put it there in the first place was because it felt nice to have all the colors code self-contained in that class file. Now that we've wrapped up that PR, there's already some colors code in `functions.php`, so I think moving that enqueue there makes sense.

**Comment by kjellr** [comment]
I'm going to close this one for now since we're moving this repo over to [automattic/themes](https://github.com/automattic/themes). We can re-open a new one there if we'd still like to discuss later.
