### ISSUE TITLE
Seedlet Child Theme DevEx

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#142]
I'd like to gather input on how to optimize the Varya/Root child-theme development experience. It would be useful to gather some learnings from working with Varia and maintaining its child themes as well.

My main question at this point is, does the child-theme approach make the most sense for our goals? Or does it make more sense to create forks of Varya and ship self-contained, standalone themes? 

Regardless of the path we decide, some principles for the theme development experience to aspire towards could include:

1. It makes sense to novice theme developers.
2. The documentation is great.
3. The ratio of the amount of code one needs to change to get significant visual variety is _low_.

Would love your input on any of the above.

**Comment by ianstewart** [comment]
> My main question at this point is, does the child-theme approach make the most sense for our goals? Or does it make more sense to create forks of Varya and ship self-contained, standalone themes?

Curious, for a practical example, how long it would take to turn [Maywood](https://maywooddemo.wordpress.com/) into a Varya/Root theme with either approach.

And then, as a separate thing, what the average weekly maintenance time would look like in both cases.

**Comment by jffng** [comment]
> how long it would take to turn Maywood into a Varya/Root theme with either approach.

I would guess the difference in development time between approaches is negligible because they would require the same amount of code to be re-written: updating typography styles, color palettes, changing variables, modifying a handful of template parts (e.g. header and footer).  

> what the average weekly maintenance time would look like in both cases.

What has maintenance looked like in Varia? When you encounter a regression, do you typically have to fix the bug upstream in Varia, then issue child-theme specific fixes, or both?

I also wonder what approach would be preferred from a TRT perspective, since the child theme differences are minimal by design, sort of going against this guideline: https://github.com/WPTRT/Theme-Requirements/blob/master/ChildThemes/IncludeMoreThanMinorChanges.md

**Comment by ianstewart** [comment]
I think the TRT rule is resolved by the design principle you all have.

> The ratio of the amount of code one needs to change to get significant visual variety is low.

High visual variety. iirc that rule is there to stop "spam" themes from being added where someone would fork a popular theme and make minor changes in order to masquerade as or steal the thunder of another theme without adding things of value.

High visual variety with few code changes is a plus for everyone. :)

**Comment by ianstewart** [comment]
> What has maintenance looked like in Varia? When you encounter a regression, do you typically have to fix the bug upstream in Varia, then issue child-theme specific fixes, or both?

@allancole and @michaeldcain have both made a bunch of changes across the board recently, I think. Thoughts, Allan and Cain?

**Comment by kjellr** [comment]
> What has maintenance looked like in Varia? When you encounter a regression, do you typically have to fix the bug upstream in Varia, then issue child-theme specific fixes, or both?

In general with Varia, it seems like most changes need to be make _only_ in Varia, but any stylesheet changes that happen there need to be recompiled for the child themes. I don't think that second step will need to happen in Varya because of our use of CSS variables, but @allancole can correct me there.

**Comment by kjellr** [comment]
I'm going to close this one for now since we're moving this repo over to [automattic/themes](https://github.com/automattic/themes). We can re-open a new one there if we'd still like to discuss later.
