### ISSUE TITLE
Varya: color profiles

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#143]
I don't fully understand color profiles in browser, but I've always found the colors less "vibrant" when I take the hex values from Figma and put them straight into CSS and view them in the browser.

Here's my limited understanding of the problem: Different platforms and apps use different color profiles. Hex can't represent all the possible color combinations a display is capable of rendering, so different profiles translate them ... differently. This results result in imperfect color translation.

Take our primary color for example:

Figma (#A36265) | Chrome (#A36265)
------ | ------
<img width="156" alt="Screen Shot 2020-05-11 at 5 21 36 PM" src="https://user-images.githubusercontent.com/5375500/81613128-e6420b00-93ab-11ea-840b-b7c131d220d5.png">|<img width="156" alt="Screen Shot 2020-05-11 at 5 13 05 PM" src="https://user-images.githubusercontent.com/5375500/81612371-ba725580-93aa-11ea-9f41-9e9eb9bbd749.png">

Per a discussion in the #design slack channel, I recently discovered the SIP color dropper tool. When I use this tool to sample the primary color in Figma, it gives me a different hex value (#AC5E64) than what Figma reports. Placing this value in CSS results in a closer color than to the one selected in the design.

Figma (#A36265) | Chrome (#AC5E64)
------ | ------
<img width="156" alt="Screen Shot 2020-05-11 at 5 21 36 PM" src="https://user-images.githubusercontent.com/5375500/81613128-e6420b00-93ab-11ea-840b-b7c131d220d5.png">|<img width="156" alt="Screen Shot 2020-05-11 at 5 12 40 PM" src="https://user-images.githubusercontent.com/5375500/81613195-02de4300-93ac-11ea-972c-1577933da093.png">

Are my eyes fooling me? Do you agree that the color is closer? If so, should we replace this color, even though our design documentation would be out of sync with what's represented in code? 

cc @kjellr @allancole

**Comment by jffng** [comment]
Edit after a tip from @allancole:

Switching my color profile in Figma to sRGB makes the colors in the browser and chrome exactly as far as I can tell:

Figma (#A36265) | Chrome (#A36265)
------ | ------
<img width="157" alt="Screen Shot 2020-05-11 at 5 50 47 PM" src="https://user-images.githubusercontent.com/5375500/81615694-04aa0580-93b0-11ea-9137-cd352d9b8a23.png">|<img width="157" alt="Screen Shot 2020-05-11 at 5 50 47 PM" src="https://user-images.githubusercontent.com/5375500/81612371-ba725580-93aa-11ea-9f41-9e9eb9bbd749.png">
 
Switching to sRGB "dulls" colors in comparison to the unmanaged color profile.

**Comment by kjellr** [comment]
Color profiles are some of the most confusing, frustrating things I've ever come across in my lifetime. 😭 

In a nutshell: There isn't much we can do about this, but we should have each of us designing in the sRGB space to minimize the disappointment. When translating the colors to development, we should use the Hex values from the comps, even if they look a little different: the color will vary slightly depending on computer/monitor anyway, and the Hex value is really the only thing we can hold onto if we want a consistent base value. 

I'll close this for now, but we can open new issues if specific colors looks weird in the future.
