### ISSUE TITLE
Seedlet: Custom colors show up broken on fresh install

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#174]
On a fresh install, all of the custom colors show up broken. This can be fixed by visiting the customizer, choosing to use non-default colors, and then reverting back to the default again. 

<img width="913" alt="Screen Shot 2020-06-04 at 10 16 06 AM" src="https://user-images.githubusercontent.com/1202812/83796677-6c7e0400-a66f-11ea-956d-0e366f7b66c0.png">

**Comment by kjellr** [comment]
@jffng is digging into this, but cc-ing @allancole in case you have any immediate ideas. This issue was first noticed after we renamed the theme, but it's totally possible that it existed since we built custom colors in, and that we just never noticed.

**Comment by allancole** [comment]
Ahhh, I’m about 93% sure I have a solution for this. Will try it in a PR shortly :-)
