### ISSUE TITLE
Varya: Clean up the default content widths

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#36]
The default content widths aren't correct at the moment: 

https://github.com/Automattic/themes-workspace/blob/588926a8ae2032fd9a2302ba65679da4640beffa/varya/assets/sass/structure/_responsive-logic.scss#L69-L81

A couple things to note: 

- We're currently defining `--responsive--aligndefault-width` twice there. 
- To match the comps, the max-width of the main content column should be `620px`. 
- To match the comps, the max align-wide width should be around `790px`. 

In general, @allancole can you share what each of those variables is supposed to mean? I'd assumed `--responsive--aligndefault-width` was supposed to be the default content width, but it appears that `--responsive--spacing-horizontal` is actually responsible for that. What is the difference between these two?

**Comment by allancole** [comment]
Super easy fix. 
Will get a PR up shortly :-)

**Comment by allancole** [comment]
> I'd assumed --responsive--aligndefault-width was supposed to be the default content width, but it appears that --responsive--spacing-horizontal is actually responsible for that. What is the difference between these two?

`--responsive--aligndefault-width` is the CSS-variable used for any blocks, components, or sections that need to match the `620px` max-width. It‘s a mobile-first variable so it on `:root` it needs to be 100% for mobile screens. Then as the the media queries get larger, the value in the variable changes to best fit the viewport screen until it hits `620px` wide where its stays at 620px regardless of how large the viewport gets.

`--responsive--spacing-horizontal` is the CSS-variable used to determine the horizontal margins on either side of the viewport. This is necessary to apply an _inside->out_ approach to dealing with nested alignwide/full blocks as well as the top-level blocks and sections. It’s also used to prevent blocks, sections and other areas from butting up against the edge of the viewport in awkward ways.
