### ISSUE TITLE
[Varya] Refine Post Comments

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#49]
Currently the post comments section looks like this: 
<img width="500" alt="Screen Shot 2020-04-03 at 12 19 20 PM" src="https://user-images.githubusercontent.com/5375500/78382823-6e5f1480-75a5-11ea-8bf8-db1cd7836dbf.png">

It should look like this:
<img width="500" alt="Screen Shot 2020-04-03 at 12 16 16 PM" src="https://user-images.githubusercontent.com/5375500/78382719-466fb100-75a5-11ea-8bad-d68c956968e5.png">

**Comment by kjellr** [comment]
This should be all set now that #53 was merged.
