### ISSUE TITLE
theme-dev-utils not found

### ISSUE THREAD

**Issue by mahnunchik** [Automattic/themes-workspace#51]
Hi,

I've faced with the project https://github.com/Automattic/theme-dev-utils doesn't exists.

The link from https://github.com/Automattic/themes-workspace/blob/master/varya/README.md#create-a-child-theme-manually-optional

**Comment by jeffikus** [comment]
Theme Dev Utils is a private repo and not ready for production yet. I've removed the link for now as the utility will likely be published onto npm instead.

**Comment by jeffikus** [comment]
Just further to this - the intention of this utility to create a child theme for Varya with 1 command line instruction, something like: `npm create varya-child-theme` and then with possible arguments for optional support for something like Jetpack or WooCommerce.

**Comment by jeffikus** [comment]
We're keeping it simple for now, and when it's ready I'll update the readme again :)
