### ISSUE TITLE
Varya: treatment for sticky / featured post

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#54]
This is what the current treatment for a sticky post looks like:

<img width="801" alt="Screen Shot 2020-04-08 at 10 59 17 AM" src="https://user-images.githubusercontent.com/5375500/78799596-54984580-7988-11ea-9344-038026532802.png">
 

It uses `var(--global--color-primary)` as the background color, which is black at the moment and feeling quite heavy. Should we explore a different treatment? cc @kjellr

**Comment by kjellr** [comment]
I actually like it. 😄 It feels like it's got the right level of prominence, and is a little refreshing because everything else on the page is so white and light. 

cc @melchoyce for another set of 👀.

**Comment by melchoyce** [comment]
What's the whole page look like?

**Comment by kjellr** [comment]
Here's a bit more of a complete page: 

![dotorgthemes test_](https://user-images.githubusercontent.com/1202812/78943510-010e2080-7a8a-11ea-9b40-7a95e4ebf9c6.png)

**Comment by melchoyce** [comment]
I think the heaviness can start to feel a little distracting — my eyes are drawn to that, and it remains a big blob of dark as I try to move down to the rest of the text. Maybe also try version with a thicker black outline instead of background?

**Comment by kjellr** [comment]
Here are a few more options. I think I like the "Smaller Solid Red" version the best.

Original|Border
------------|------------
![dotorgthemes test_ (1)](https://user-images.githubusercontent.com/1202812/78949322-2ce4d280-7a99-11ea-92f2-8546756dc8e9.png)|![dotorgthemes test_ (2)](https://user-images.githubusercontent.com/1202812/78949335-3110f000-7a99-11ea-88e0-704532d86d1c.png)

Smaller Solid|Smaller Border
------------|------------
![dotorgthemes test_ (3)](https://user-images.githubusercontent.com/1202812/78949381-5aca1700-7a99-11ea-8e82-99006805acb3.png)|![dotorgthemes test_ (4)](https://user-images.githubusercontent.com/1202812/78949427-877e2e80-7a99-11ea-8426-b0ac9810a6be.png)


Smaller Solid Red|Smaller Border Red
------------|------------
![dotorgthemes test_ (6)](https://user-images.githubusercontent.com/1202812/78949400-6e757d80-7a99-11ea-8bb5-1d5638b5748d.png)|![dotorgthemes test_ (5)](https://user-images.githubusercontent.com/1202812/78949399-6d445080-7a99-11ea-842b-40c96ab33cd9.png)

**Comment by melchoyce** [comment]
Yeah, I think the smaller solid red (and black, actually the reduced sizing helps) work best.
