### ISSUE TITLE
Varya: Remove global border-color variants

### ISSUE THREAD

**Issue by allancole** [Automattic/themes-workspace#57]
It’s becoming apparent that the two `-light` and `-dark` color variations for border-color are rarely used, if at all. We should consider removing them for clarity. 

https://github.com/Automattic/themes-workspace/blob/1d69ab9eadc0c8e809c7f88263b506d70fdf31f7/varya/assets/sass/abstracts/_config.scss#L46-L48

**Comment by jffng** [comment]
Noting that the following two variables are duplicates at the same level of hierarchy (`global`). 

https://github.com/Automattic/themes-workspace/blob/1d69ab9eadc0c8e809c7f88263b506d70fdf31f7/varya/assets/sass/abstracts/_config.scss#L41

https://github.com/Automattic/themes-workspace/blob/1d69ab9eadc0c8e809c7f88263b506d70fdf31f7/varya/assets/sass/abstracts/_config.scss#L45

Anecdotally, I've stumbled with how to use the foreground variables other than to color text. Would the intention be also for something like a border color?
