### ISSUE TITLE
Modal block

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#6]
**Description**
I would like for there to be a modal block that takes over the entire page, like this navigation design would: 

_Closed_ 
<img width="557" alt="Screen Shot 2020-03-06 at 5 16 24 PM" src="https://user-images.githubusercontent.com/5375500/76126950-750e6200-5fce-11ea-8f55-41b403c6b705.png">

_Open_
<img width="555" alt="Screen Shot 2020-03-06 at 5 16 14 PM" src="https://user-images.githubusercontent.com/5375500/76126955-78095280-5fce-11ea-8119-74b84b573dc4.png">

**Comment by kjellr** [comment]
I'm going to close this one for now since we're moving this repo over to [automattic/themes](https://github.com/automattic/themes), but the issue will still be readable here for posterity.
