### ISSUE TITLE
Varya: Text selection color might be too light.

### ISSUE THREAD

**Issue by allancole** [Automattic/themes-workspace#78]
The text selection color isn’t very noticeable at the moment. It currently matches the `--global--foreground-light` variable but I think a lighter version of the salmon color might be better.

Current screenshot:

![image](https://user-images.githubusercontent.com/709581/79164573-53638000-7daf-11ea-9c09-6716acb04f7a.png)

Suggested alternative: 

![image](https://user-images.githubusercontent.com/709581/79164942-206dbc00-7db0-11ea-848c-10b2cdb182bf.png)

**Comment by kjellr** [comment]
Ah, yes. I actually changed this in a PR at one point, but then forgot about it. 😄 I'll spin up a new one momentarily.
