### ISSUE TITLE
Varya: Footer treatment

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#88]
The footer should be cleaned up, as right now it can grow very long if the site has a lot of content. Currently it displays the following:

- A search input
- Recent Posts (5 max)
- Recent Comments (6 max)
- Archives (no max)
- Categories (no max)
- Meta
- A theme WordPress credit line

One related consideration from the Theme Unit Test is that the theme must "incorporate both the 'Tag' and 'Category' taxonomies in some manner". Though I believe we meet this requirement by displaying the tags and categories in the meta of each post.

<details><summary>Current footer design (click to expand)</summary>
<img width="510" alt="Screen Shot 2020-04-15 at 3 31 30 PM" src="https://user-images.githubusercontent.com/5375500/79380576-9bf57780-7f2e-11ea-9757-7fb3910e110f.png">
<img width="559" alt="Screen Shot 2020-04-15 at 3 31 39 PM" src="https://user-images.githubusercontent.com/5375500/79380990-3e155f80-7f2f-11ea-9339-f504973b1c10.png">
</details>

**Comment by allancole** [comment]
Yeah, these are all just widgets. By default the footer widget area is empty, so new sites won’t see anything in the footer but credits and maybe the footer menu if they’ve activated it. 

> the theme must "incorporate both the 'Tag' and 'Category' taxonomies in some manner".

I haven’t read through the TUT in a while, but I’m pretty sure this is less about displaying widgets or category/tag lists. Seems to be more about having the ability to set categories and tags on a post, and then having a way to access a category or tag archive based on the term—all of which Varya already does via the entry meta links (c/o `_s`  :-) )

**Comment by jffng** [comment]
> By default the footer widget area is empty, so new sites won’t see anything in the footer but credits and maybe the footer menu if they’ve activated it

Ohh got it! So I will close this issue then. 

Yeah I think you're right about the categories and tags being the ability to set them on a post, and access an archive.
