### ISSUE TITLE
Varya: 404 page treatment

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#89]
Currently the 404 page displays the following:

<img width="687" alt="Screen Shot 2020-04-15 at 3 46 47 PM" src="https://user-images.githubusercontent.com/5375500/79381708-6487ca80-7f30-11ea-8503-2b3e28d92156.png">

I think it's okay, but we may want to consider dropping the search input if it's already at the top of the footer.

**Comment by allancole** [comment]
That second search form is likely coming from the footer widget area. If users don’t have a search form in the footer widgets, than they’ll see just one search form.

**Comment by jffng** [comment]
Got it! 

Thoughts on adjusting the search template to use more of a flex layout like so?

<img width="700" alt="Screen Shot 2020-04-15 at 5 26 13 PM" src="https://user-images.githubusercontent.com/5375500/79390763-4f199d00-7f3e-11ea-8f65-7a0bfde594e6.png">

**Comment by allancole** [comment]
Yup, I like that. Go for it! 👍
