### ISSUE TITLE
Varya: Read More link doesn't display

### ISSUE THREAD

**Issue by jffng** [Automattic/themes-workspace#90]
Per the theme unit test, the theme should support the "More" tag / block, meaning a "Read More" link should appear and link to a single post at the "More" tag location.

When I add a "More" block, the content is truncated properly but the link doesn't appear on the front-end:

<img width="681" alt="Screen Shot 2020-04-15 at 3 58 07 PM" src="https://user-images.githubusercontent.com/5375500/79382891-402ced80-7f32-11ea-8aba-44a3651b96f9.png">

**Comment by allancole** [comment]
Weird, here’s what I’m getting on Master:

![image](https://user-images.githubusercontent.com/709581/79387186-39ee3f80-7f39-11ea-9c31-b65631f4988f.png)

Probably doesn’t need to be centered but is appearing for me.

**Comment by jffng** [comment]
I did a bit more digging, and found that the More link appears on the front page if you've selected it to display latest posts. 

But when I access a category or search page, the same post doesn't show the More link. Is this the expected behavior?

**Front page showing a post with a More block**
<img width="731" alt="Screen Shot 2020-04-16 at 4 12 17 PM" src="https://user-images.githubusercontent.com/5375500/79502311-69668000-7ffd-11ea-972d-920abef695e3.png">

**Search results page showing the same post, with no link**
<img width="745" alt="Screen Shot 2020-04-16 at 4 13 30 PM" src="https://user-images.githubusercontent.com/5375500/79502410-9155e380-7ffd-11ea-88d6-a651b1786c9c.png">

Also yeah, we should left align it.

**Comment by allancole** [comment]
Ahhh, I think I know why that is… let me try something and report back.

**Comment by allancole** [comment]
This still seems to be working as expected for me. I thought the `content-excerpt.php` file had the wrong excerpt function in there but its actually: 

Archives | Blog feed | Editor
------------|------------|------------
![image](https://user-images.githubusercontent.com/709581/79510843-2233bb80-800c-11ea-9ed4-4f268f3970a6.png)|![image](https://user-images.githubusercontent.com/709581/79510905-40012080-800c-11ea-9745-a2d4eac70558.png)|![image](https://user-images.githubusercontent.com/709581/79511035-7dfe4480-800c-11ea-92f9-1da5023e79ab.png)

**Comment by jffng** [comment]
Closing this as I can't reliable reproduce.
