### ISSUE TITLE
Varya: Figure out a way to include a narrow color stripe behind group block content

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#92]
As per the comps here: 

![Screen Shot 2020-04-16 at 3 32 48 PM](https://user-images.githubusercontent.com/1202812/79498565-88621380-7ff7-11ea-8c79-0a4ec9ee6a04.png)

Could be a group block style with some weird background position adjustments? Or perhaps a gradient background with 3 color stops (white/pink/white)? Needs some experimentation.

**Comment by jffng** [comment]
> Could be a group block style with some weird background position adjustments?

I tried this out in [an earlier PR](https://github.com/Automattic/themes-workspace/pull/16/commits/ad346582e058084f4995ecf98e102ab5249c0e6b#diff-bebd17ac9d461436bb9e845a929402f9R106-R112
) as a group block style. The effect can somewhat be achieved with negative margins on the container and inner elements.

A gradient treatment might be more adaptive though, so you're not relying on percentages or v-units.
