### ISSUE TITLE
Varya: Add gradient presets

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#93]
We need to add some [custom gradient presets](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-gradient-presets) into the theme. 

We should include some with abrupt transitions like this... 

![Screen Shot 2020-04-16 at 3 45 47 PM](https://user-images.githubusercontent.com/1202812/79499883-9c0e7980-7ff9-11ea-8860-20ee84d9c4ac.png)

... to be used to create this representation from the comps: 

![Screen Shot 2020-04-16 at 3 45 56 PM](https://user-images.githubusercontent.com/1202812/79499899-a3358780-7ff9-11ea-962d-ad0271d6f5de.png)

**Comment by jffng** [comment]
Closed by #95.
