### ISSUE TITLE
Generate stylesheet of vanilla variables for Seedlet child themes

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes-workspace#96]
Varya currently includes opinionated default styles. We need to generate an example of a more "vanilla" variables stylesheet that can be used in Child themes that want to reset and start from a more unstyled base. 

Eventually, this stylesheet will be optionally pulled in when generating a new theme via the Varya build tool.

**Comment by jffng** [comment]
@kjellr is this issue still relevant? Can the goal (to identify the variables that need be changed to alter the fundamental theme design) be extrapolated from the work on sk8prk?

**Comment by kjellr** [comment]
Hmm. Yeah, I think this issue is still valid. Sk8prk can definitely help us inform the goal here.

**Comment by kjellr** [comment]
I've migrated this over here: https://github.com/Automattic/themes/issues/2133
